# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playerinfo.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1020, 813)
        self.Playerinfo = QtWidgets.QLabel(Dialog)
        self.Playerinfo.setGeometry(QtCore.QRect(130, 330, 211, 51))
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(28)
        self.Playerinfo.setFont(font)
        self.Playerinfo.setObjectName("Playerinfo")
        self.Playerinfo_2 = QtWidgets.QLabel(Dialog)
        self.Playerinfo_2.setGeometry(QtCore.QRect(130, 420, 211, 51))
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(28)
        self.Playerinfo_2.setFont(font)
        self.Playerinfo_2.setObjectName("Playerinfo_2")
        self.Playerinfo_3 = QtWidgets.QLabel(Dialog)
        self.Playerinfo_3.setGeometry(QtCore.QRect(130, 520, 211, 51))
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(28)
        self.Playerinfo_3.setFont(font)
        self.Playerinfo_3.setObjectName("Playerinfo_3")
        self.Playerinfo_4 = QtWidgets.QLabel(Dialog)
        self.Playerinfo_4.setGeometry(QtCore.QRect(130, 610, 221, 51))
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(28)
        self.Playerinfo_4.setFont(font)
        self.Playerinfo_4.setObjectName("Playerinfo_4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(230, 50, 561, 101))
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 1021, 821))
        self.graphicsView.setObjectName("graphicsView")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(410, 330, 261, 51))
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(28)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(410, 420, 261, 51))
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(28)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(410, 520, 261, 51))
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(28)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(410, 610, 261, 51))
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(28)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(530, 460, 521, 361))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 341, 171))
        self.label_3.setMinimumSize(QtCore.QSize(341, 0))
        self.label_3.setMaximumSize(QtCore.QSize(341, 16777215))
        self.label_3.setObjectName("label_3")
        self.GameStart = QtWidgets.QPushButton(Dialog)
        self.GameStart.setGeometry(QtCore.QRect(130, 700, 181, 61))
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(20)
        self.GameStart.setFont(font)
        self.GameStart.setObjectName("GameStart")
        self.Player1_PieceNum = QtWidgets.QSpinBox(Dialog)
        self.Player1_PieceNum.setGeometry(QtCore.QRect(720, 200, 91, 31))
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        self.Player1_PieceNum.setFont(font)
        self.Player1_PieceNum.setMinimum(2)
        self.Player1_PieceNum.setMaximum(5)
        self.Player1_PieceNum.setObjectName("Player1_PieceNum")
        self.ExitBtn = QtWidgets.QPushButton(Dialog)
        self.ExitBtn.setGeometry(QtCore.QRect(370, 700, 181, 61))
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(20)
        self.ExitBtn.setFont(font)
        self.ExitBtn.setObjectName("ExitBtn")
        self.PieceNum = QtWidgets.QLabel(Dialog)
        self.PieceNum.setGeometry(QtCore.QRect(520, 190, 141, 51))
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(24)
        self.PieceNum.setFont(font)
        self.PieceNum.setObjectName("PieceNum")
        self.PlayerNum = QtWidgets.QSpinBox(Dialog)
        self.PlayerNum.setGeometry(QtCore.QRect(370, 200, 91, 31))
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        self.PlayerNum.setFont(font)
        self.PlayerNum.setMinimum(2)
        self.PlayerNum.setMaximum(4)
        self.PlayerNum.setObjectName("PlayerNum")
        self.PlayerNum_Txt = QtWidgets.QLabel(Dialog)
        self.PlayerNum_Txt.setGeometry(QtCore.QRect(130, 190, 201, 51))
        font = QtGui.QFont()
        font.setFamily("배달의민족 주아")
        font.setPointSize(24)
        self.PlayerNum_Txt.setFont(font)
        self.PlayerNum_Txt.setObjectName("PlayerNum_Txt")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(430, 260, 131, 41))
        self.pushButton.setObjectName("pushButton")
        self.graphicsView.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.Playerinfo.raise_()
        self.Playerinfo_2.raise_()
        self.Playerinfo_3.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.Playerinfo_4.raise_()
        self.GameStart.raise_()
        self.Player1_PieceNum.raise_()
        self.ExitBtn.raise_()
        self.PieceNum.raise_()
        self.PlayerNum.raise_()
        self.PlayerNum_Txt.raise_()
        self.pushButton.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Playerinfo.setText(_translate("Dialog", "플레이어 1 :"))
        self.Playerinfo_2.setText(_translate("Dialog", "플레이어 2 :"))
        self.Playerinfo_3.setText(_translate("Dialog", "플레이어 3 :"))
        self.Playerinfo_4.setText(_translate("Dialog", "플레이어 4 :"))
        self.label.setText(_translate("Dialog", "플레이어 정보 입력"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/imgs/yutnori_fam.jpg\"/></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/imgs/yut001.jpg\"/></p></body></html>"))
        self.GameStart.setText(_translate("Dialog", "Game Start"))
        self.ExitBtn.setText(_translate("Dialog", "EXIT"))
        self.PieceNum.setText(_translate("Dialog", "말의 갯수"))
        self.PlayerNum_Txt.setText(_translate("Dialog", "플레이어 명수"))
        self.pushButton.setText(_translate("Dialog", "확인"))

"""import myres_rc"""

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

